apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
spec:
  selector:
    ENV: my-app
  ports:
    - protocol: TCP
      port: 80   #Service Port no. ~ Cluster IP
      targetPort: 82   #Container Port number running inside the Pod

#Service = Selector
#Pods/Deployments = Labels
#Service type was not defined as ClusterIP is Default type of Service in Kubernetes. So, it will be created as ClusterIP type Service.
---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    ENV: my-app 
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 82    
    - name: jenkins-container
      image: jenkins/jenkins:lts
      ports:
        - containerPort: 8080    