apiVersion: v1
kind: Service
metadata: 
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: dev  
  ports:
    - protocol: TCP
      port: 80   #Service Port no. ~ Cluster IP
      targetPort: 80   #Container Port number running inside the Pod  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev  
    spec:
      containers:
        - name: apache-container
          image: httpd:latest
          ports: 
            - containerPort: 80







