apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: dev
  ports:
    - protocol: TCP
      port: 80   #Service Port no. ~ Cluster IP
      targetPort: 80   #Container Port number running inside the Pod
      nodePort: 30080   #NodePort number to access the Service from outside of the Cluster 

 #To access from Web Workernode Ip Address: NodePort Port Number. Example: http://<NodeIP>:30080     

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80    
        - name: jenkins-container
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080