apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: development
spec:
  replicas: 3 # Replicas for Pods
  selector:
    matchLabels:
      app: nginx-rs
  template:
    metadata:
      labels:
        app: nginx-rs
    spec:
      containers:
      - name: my-app
        image: nginx:1.14.2