apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  namespace: nginx-dev

spec:
  type: NodePort                   # Access application from browser

  selector:
    app: nginx

  ports:
  - port: 80
    targetPort: 80